baseurl = "/"
title = "Ryan Estrellado"
copyright = "Copyright &copy; 2017 - Ryan Estrellado"
canonifyurls = false
theme = "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Ryan Estrellado"
    github = "restrellado"
    gitlab = ""
    linkedin = "ryanestrellado"
    facebook = ""
    twitter = "ryanes"
    instagram = "" 

[params]
    tagline = "I work in public education and love data science." 

[permalinks]
  post = "/:year/:month/:filename/"


